class Env(dict):
    def __setitem__(self, key, value):
        key = key.upper()
        super().__setitem__(key, value)

    # def __getitem__(self, __key: _KT) -> _VT: ...
    # def __setitem__(self, __key: _KT, __value: _VT) -> None: ...
    # def __delitem__(self, __key: _KT) -> None: ...
